//
//  TranscriptModel.swift
//  MeetingSonar
//
//  Created by MeetingSonar Team.
//  Copyright © 2024 MeetingSonar. All rights reserved.
//

import Foundation

/// Data model representing a transcript file.
/// Maps to the JSON structure generated by ASRService.
struct TranscriptModel: Codable {
    let metadata: TranscriptMetadata
    let segments: [TranscriptSegment]
}

struct TranscriptMetadata: Codable {
    let duration: TimeInterval
    let processingTime: TimeInterval
    let rtf: Double
}

struct TranscriptSegment: Codable, Identifiable, Equatable {
    // Generate a stable ID based on start time effectively, or just generic UUID if needed.
    // However, ASRService doesn't output IDs. We can compute one or us UUID().
    // Using UUID() makes it Codable if we make it optional or give default.
    // Ideally we want stable identity for SwiftUI List.
    // Let's use `start` as a key component or just add an `id` property computed after decode if possible.
    // Swift Codable doesn't support post-decode hooks easily on structs without custom init.
    // Simple approach: Use UUID() as default value, but that changes on every load. 
    // Better: use combination of start_end as ID string?
    
    var id: String {
        return "\(start)-\(end)"
    }
    
    let start: TimeInterval
    let end: TimeInterval
    let text: String
    
    // Coding keys to match JSON (which doesn't have 'id')
    enum CodingKeys: String, CodingKey {
        case start, end, text
    }
}
